routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/', '/app/login', 301);

Route::get('franchises', 'AppController@getFranchises')->name('get.franchises');

//Auth::routes();

app/Models/Tenant/Payment.php
<?php

namespace App\Models\Tenant;

use App\Enums;
use App\Models;
use App\Traits\EncryptModel;
use Konekt\Enum\Eloquent\CastsEnums;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Builder;
use Tenancy\Affects\Connections\Support\Traits\OnTenant;

class Payment extends Model
{
    use OnTenant,
        CastsEnums,
        EncryptModel;

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'payments';

    /**
     * The relationships that should always be loaded.
     *
     * @var array
     */
    protected $with = [];

    /**
     * The attributes that aren't mass assignable.
     *
     * @var array
     */
    protected $guarded = ['id', 'created_at', 'updated_at'];

    protected $enums = [
        'payment_method' => Enums\PaymentMethod::class,
        'status' => Enums\PaymentStatus::class,
    ];

    /** Relations */
    public function coursable()
    {
        return $this->belongsTo(Coursable::class);
    }

    public function user()
    {
        return $this->belongsTo(Models\User::class);
    }

    public function bank()
    {
        return $this->belongsTo(Bank::class);
    }

    public function plan()
    {
        return $this->belongsTo(Plan::class);
    }

    /** Attributes */
    protected function getVoucherAttribute()
    {
        $disk = \Storage::disk(request()->is('app/*') ? 'tenant' : 'public');
        return str_replace(
            storage_path('app/'),
            '',
            $disk->path($this->voucher_path)
        );
    }
}

app/Models/Tenant/Plan.php
<?php

namespace App\Models\Tenant;

use App\Enums;
use App\Traits\EncryptModel;
use Konekt\Enum\Eloquent\CastsEnums;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\SoftDeletes;
use Tenancy\Affects\Connections\Support\Traits\OnTenant;

class Plan extends Model
{
    use OnTenant,
        CastsEnums,
        SoftDeletes,
        EncryptModel;

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'plans';

    /**
     * The relationships that should always be loaded.
     *
     * @var array
     */
    protected $with = ['features'];

    /**
     * The attributes that aren't mass assignable.
     *
     * @var array
     */
    protected $guarded = ['id', 'created_at', 'updated_at', 'deleted_at'];

    protected $enums = [
        'interval_unit' => Enums\PlanInterval::class,
    ];

    /** Relations */
    public function branches()
    {
        return $this->belongsToMany(Branch::class);
    }

    public function features()
    {
        return $this->hasMany(PlanFeature::class);
    }

    /** Attributes */
    public function getPlanAttribute()
    {
        return $this;
    }

    public function getFullnameAttribute()
    {
        return "{$this->code} {$this->name} ({$this->interval_unit})";
    }

    public function getWithInscriptionAttribute()
    {
        return (boolean) $this->features()->where('type', 'inscription')->count();
    }
}

app/Models/User.php
<?php

namespace App\Models;

use App\Traits;
use App\Models\Tenant;
use Tenancy\Environment;
use App\Traits\GlobalModelConnection;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Tenancy\Affects\Connections\Support\Traits\OnTenant;
use Caffeinated\Shinobi\Concerns\HasRolesAndPermissions;

class User extends Authenticatable
{
    use Notifiable,
        SoftDeletes,
        Traits\UserProfile,
        Traits\EncryptModel,
        HasRolesAndPermissions,
        Traits\GlobalModelConnection;

    /**
     * The attributes that aren't mass assignable.
     *
     * @var array
     */
    protected $guarded = ['id', 'created_at', 'updated_at', 'deleted_at'];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * The relationships that should always be loaded.
     *
     * @var array
     */
    protected $with = [];

    /** Delete Relationships */
    public function deleteRelationships()
    {
        //
    }

    /** Relationships */
    public function branches()
    {
        return $this->belongsToMany(Tenant\Branch::class);
    }

    public function staff()
    {
        return $this->hasOne(Tenant\Staff::class);
    }

    public function personalData()
    {
        return $this->hasOne(Tenant\PersonalData::class);
    }

    public function languages()
    {
        $db = config('database.connections.tenant.database');
        return $this->belongsToMany(System\Language::class, $db.".language_user")
                    ->using(Tenant\LanguageUser::class);
    }

    public function studentType()
    {
        return $this->belongsToMany(Tenant\StudentType::class);
    }

    public function points()
    {
        return $this->hasMany(Tenant\TeacherPoint::class);
    }

    public function enrollment()
    {
        return $this->hasOne(Tenant\StudentEnrollment::class);
    }

    public function parent()
    {
        return $this->belongsToMany(
            User::class, 'parent_children', 'children_id', 'parent_id'
        );
    }

    public function children()
    {
        return $this->belongsToMany(
            User::class, 'parent_children', 'parent_id', 'children_id'
        );
    }

    public function schedules()
    {
        return $this->hasMany(Tenant\Schedule::class);
    }

    public function coursables()
    {
        return $this->hasMany(Tenant\Coursable::class);
    }

    public function courses()
    {
        return $this->belongsToMany(Tenant\Coursable::class)->withPivot('plan_id');
    }

    /** Scopes */
    public function scopeFindRole($query, $value)
    {
        return $query->whereHas('roles', function (Builder $query) use ($value) {
            $query->where('slug', $value);
        });
    }

    public function scopeTeachers($query, $type)
    {
        return $query->whereHas('roles', function (Builder $query) {
            $query->where('slug', 'teacher');
        })->whereHas('staff', function (Builder $query) use ($type) {
            $query->where('type', $type->value());
        });
    }

    public function scopeStudents($query, $status)
    {
        return $query->whereHas('roles', function (Builder $query) {
            $query->where('slug', 'student');
        })->whereHas('enrollment', function (Builder $query) use ($status) {
            $query->where('status', $status->value());
        });
    }

    public function scopeWhereBranch($query, $branch)
    {
        return $query->whereHas('branches', function($query) use ($branch) {
            $query->where('id', $branch);
        });
    }

    public function scopeWhereStudentType($query, $type)
    {
        return $query->whereHas('studentType', function($query) use ($type) {
            $query->where('id', $type);
        });
    }

    public function scopeWhereScheduleDay($query, $days)
    {
        return $query->whereHas('schedules', function($query) use ($days) {
            $query->whereIn('day', $days);
        });
    }

    public function scopeWhereScheduleTime($query, $times)
    {
        return $query->whereHas('schedules', function($query) use ($times) {
            $query->where('start_time', $times['start_time'])
                  ->where('end_time', $times['end_time']);
        });
    }

    public function scopeWhereEnrollmentType($query, $type)
    {
        return $query->whereHas('enrollment', function($query) use ($type) {
            $query->where('student_type_id', $type);
        });
    }

    public function scopeWhereCourse($query, $value)
    {
        return $query->whereHas('courses', function($query) use ($value) {
            $query->where('coursable_id', $value);
        });
    }

    public function scopeWhereDoesntHaveCourse($query, $value)
    {
        return $query->whereDoesntHave('courses', function($query) use ($value) {
            $query->where('coursable_id', $value);
        });
    }

    public function scopeRepresentatives($query)
    {
        return $query->whereHas('roles', function (Builder $query) {
            $query->where('slug', 'representative');
        });
    }

    public function scopeFindByCi($query, $value)
    {
        return $query->whereHas('roles', function (Builder $query) {
            $query->where('slug', 'representative');
        })->whereHas('personalData', function (Builder $query) use ($value) {
            $query->where('ci', $value);
        });
    }

    public function scopeDoesntHaveCourse($query, $value)
    {
        return $query->whereDoesntHave('coursables', function(Builder $query) use ($value) {
            $query->whereHas('days', function(Builder $query) use ($value) {
                    $query->whereIn('day', $value['days']);
            })
            ->where('schedule_id', $value['schedule_id']);
        });
    }

    /** Attributes */
    public function getRoleAttribute()
    {
        return $this->roles->first();
    }

    public function getBranchAttribute()
    {
        return $this->branches->first();
    }

    public function getAddressAttribute()
    {
        return $this->personalData->address;
    }

    public function getStatusAttribute()
    {
        return $this->staff->status;
    }

    public function getTypeAttribute()
    {
        return $this->staff->type;
    }

    public function getRatingsAttribute()
    {
        if ($point = $this->points->where('type', 'general')->first())
            return $point->value;

        return '0.00';
    }

    public function getUserAttribute()
    {
        if ($this->role->slug != 'student')
            $more = [
                'contract_start' => $this->staff
                    ? $this->staff->contract_start : null,
                'contract_end' => $this->staff
                    ? $this->staff->contract_end : null,
                'ranting' => $this->points->pluck('value', 'type'),
                'student' => $this->studentType->pluck('id'),
            ];
        elseif ($this->enrollment)
            $more = ['student' => $this->enrollment->student_type_id];
        else
            $more = [];

        return (Object) array_merge(
            $this->only('username', 'email', 'id'),
            array_merge(
                [
                    'role' => $this->role->slug,
                    'branches' => $this->branches->pluck('id')->toArray(),
                    'languages'=> $this->languages->pluck('id'),
                ],
                $more
            )
        );
    }

    public function getAcademicAttribute()
    {
        if ($data = $this->personalData->academics->first())
            return (Object) array_merge(
                $data->only('dicipline', 'graduate_year'),
                [
                    'type' => $data->type->value(),
                    'title' => $data->title ? $data->title->value() : null,
                    'institution' => $data->institution->name,
                    'is_graduated' => !$data->is_graduated
                ]
            );
        else
            return null;
    }

    public function getRepresentativeAttribute()
    {
        if ($parent = $this->parent->first())
            return (Object) array_merge(
                $parent->personalData->toArray(),
                [ 'profile_photo' => $parent->profile_photo ]
            );
    }

    public function getCiStudentAttribute()
    {
        $ci = $this->personalData->ci;
        $year = $this->personalData->birthdate_year;
        $n = $this->children->count() + 1;

        return "{$n}{$year}{$ci}";
    }

    public function getProfileIsCompleteAttribute ()
    {
        $boo = true;
        $data = collect($this->personalData->toArray())->except(['profile_photo', 'address']);

        foreach ($data as $key => $val)
            if (!$val)
                $boo = false;

        return $boo;
    }
}

app/Http/Controllers/Tenant/PaymentController.php
<?php

namespace App\Http\Controllers\Tenant;

use App\Enums;
use App\Models\Tenant;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use App\Http\Controllers\Controller;
use Inspector\Laravel\Facades\Inspector;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use App\Repositories\Tenant\PaymentRepositoryInterface as PaymentRepository;

class PaymentController extends Controller
{
    /** @var PaymentRepositoryInterface */
    private $repository;

    public function __construct(PaymentRepository $repository) {
        $this->middleware('auth');
        $this->repository = $repository;

        \View::share('pageConfigs', [
            'pageHeader' => false
        ]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('app.payment.index')->with([
            'rows' => $this->repository->all()
        ]);
    }

    public function indexAPI(Request $request)
    {
        try {
            return response()->json(
                $this->repository->getPlanDues($request->all()),
            200);
        } catch (\Exception $e) {
            DB::connection('tenant')->rollBack();
            Inspector::reportException($e);
            Log::debug($e->getMessage());
            return response()->json(['error' => $e->getMessage()], 500);
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('app.payment.create')->with(
            $this->repository->with()
        );
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try {
            DB::connection('tenant')->beginTransaction();

            $this->repository->create(
                $request->except(['_token', 'branches'])
            );

            DB::connection('tenant')->commit();
            return redirect(tenant_route('payments.index'))
                    ->with('success', __(':name has been created', [
                        'name' => ucfirst(__('Payment') )
                    ]));
        } catch (\Exception $e) {
            DB::connection('tenant')->rollBack();
            Inspector::reportException($e);
            Log::debug($e->getMessage());
            return redirect()->back()
                    ->with('error', __('Error: :msg', ['msg' => $e->getMessage()]));
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($code, $id)
    {
        $data = $this->repository->model->where('code', $id)->get();
        $plan = $data->first()->plan;
        return view('app.payment.show', compact('data', 'plan'))->with(
            $this->repository::with()
        );
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function manager(Request $request)
    {
        try {
            DB::connection('tenant')->beginTransaction();
            $this->repository->manager(
                $request->except(['_token', 'id']),
                $request->id
            );
            DB::connection('tenant')->commit();
        } catch (ModelNotFoundException $e) {
            DB::connection('tenant')->rollBack();
            return response()->json(['error' => $e->getMessage()], 404);
        } catch (\Exception $e) {
            DB::connection('tenant')->rollBack();
            return response()->json(['error' => $e->getMessage()], 500);
        }
    }
}

resources/views/app/payment/_form.blade.php
<div id="jumbotron" class="jumbotron p-1">
  <h4 class="display-5">
    {{ __('Payment plan') }}: <span id="plan"></span>
  </h4>
  <div class="d-flex justify-content-between">
    <div>
      {{ __('Dues') }}: <span id="dues_count">0</span>/<small id="dues_total">0</small>
    </div>
    <div>
      {{ __('Fee Amount ') }}: $<span id="due_paid">0.00</span>
    </div>
    <div>
      {{ __('Total to pay ') }}: $<span id="total_paid">0.00</span>
    </div>
  </div>
</div>

<div id="form-payment" class="row">
  <div class="form-group col-sm-6">
    <label>{{ __('Payment method') }}</label>
    {{
      Form::select(
        'payment_method',
        $paymentMethods,
        old("payment_method"),
        [
          'id' => 'payment_method',
          'class' => 'form-control',
          'placeholder' => __('Select :name', [ 'name' => '']),
          'required',
        ]
      )
    }}
  </div>

  <div class="form-group col-sm-6 d-none">
    <label>{{ __('Bank') }}</label>
    {!!
      Form::text(
        'bank',
        old('bank'),
        [
          'id' => 'bank',
          'class' => 'form-control',
          'autocomplete' => 'off',
        ]
      )
    !!}
  </div>

  <div class="form-group col-sm-6">
    <label>{{ __('Amount') }}</label>
    {!!
      Form::text(
        'amount',
        old('amount'),
        [
          'id' => 'amount',
          'class' => 'form-control money',
          'required'
        ]
      )
    !!}
  </div>

  <div class="form-group col-sm-12">
    <label>{{ __('Voucher') }}</label>
    {!!
      Form::file(
        'voucher_path',
        [
          'id' => 'voucher',
          'class' => 'form-control',
          'required'
        ]
      )
    !!}
  </div>
</div>

<div
  id="success-payment"
  class="swal2-popup swal2-modal swal2-icon-success swal2-show border mt-1 d-none"
  style="display: flex;"
>
  <div class="swal2-header">
    <div class="swal2-icon swal2-success swal2-icon-show" style="display: flex;">
      <div class="swal2-success-circular-line-left" style="background-color: rgb(255, 255, 255);"></div>
      <span class="swal2-success-line-tip"></span> <span class="swal2-success-line-long"></span>
      <div class="swal2-success-ring"></div> <div class="swal2-success-fix" style="background-color: rgb(255, 255, 255);"></div>
      <div class="swal2-success-circular-line-right" style="background-color: rgb(255, 255, 255);"></div>
    </div>
    <h2 class="swal2-title" id="swal2-title" style="display: flex;">
      {{ __('Fully paid course ') }}
    </h2>
  </div>
</div>
@section('vendor-style')
  @parent
  <link rel="stylesheet" href="{{ asset(mix('vendors/css/autocomplete/autocomplete.css')) }}">
@endsection
@section('vendor-script')
  @parent
  <script src="{{ asset(mix('vendors/js/mask/jquery.mask.min.js')) }}"></script>
  <script src="{{ asset(mix('vendors/js/autocomplete/autocomplete.js')) }}"></script>
@endsection
@section('page-script')
  @parent
  <script>
    $('.money').mask("#,##0.00", {reverse: true});

    $('#payment_method').change(function() {
      let val = $(this).val();

      if (val == 'wire_transfer' || val == 'app_transfer') {
        $('#bank').parent().removeClass('d-none');
        $('#voucher').parent().removeClass('col-sm-12');
        $('#voucher').parent().addClass('col-sm-6');
        autocomplete(document.getElementById("bank"), filterBank(val));
      } else {
        $('#bank').parent().addClass('d-none');
        $('#voucher').parent().removeClass('col-sm-6');
        $('#voucher').parent().addClass('col-sm-12');
        $('#bank').val('');
      }
    });

    function filterBank(type) {
      let arry = [];
      let data = {!! $banks->toJson() !!};
      data.filter(item => item.type == type).forEach(item => arry.push(item.name));

      return arry;
    }

  </script>
@endsection

resources/views/app/payment/_table.blade.php
<div class="table-responsive">
  <table class="table">
    <thead>
        <tr>
          <th>{{ __('Date') }}</th>
          <th>{{ __('Code') }}</th>
          <th>{{ __('Course') }}</th>
          <th>{{ __('Student') }}</th>
          <th>{{ __('Amount') }}</th>
          <th>{{ __('Status') }}</th>
        </tr>
    </thead>
    <tbody>
      @foreach($rows as $key => $data)
        @php
          $row = $data->first();
        @endphp
        <tr id="row-{{ $key }}">
          <td>{{ $row->created_at->toFormattedDateString()}}</td>
          <td>
            <a href="{{ tenant_route('payments.show', [$row->code]) }}">
              {{ $row->code }}
            </a>
          </td>
          <td>
            {{ $row->coursable->course->name }} {{ $row->coursable->course->level->name }}
          </td>
          <td>{{ $row->user->fullname }}</td>
          <td>{{ number_format($data->sum('amount'), 2) }}</td>
          <td>
            <span
              class="
                badge
                badge-{{ $row->status->is_approved ? 'success' : ( !$row->status->is_rejected ? 'warning' : 'danger') }}
              "
            >
              {{ $row->status }}
            </span>
          </td>
        </tr>
      @endforeach
    </tbody>
  </table>
</div>

resources/views/app/payment/show.blade.php
@extends('layouts/default')

@section('title', __('Payment').': '.$data->first()->code)

@php
  $row = $data->first();
@endphp

@section('btn-action')
  @if (!$row->status->is_approved)
    @can('payments.manager')
      <button
        class="btn btn-primary btn-manager"
        data-id="{{ $row->code }}"
        data-status="{{ $status[3] }}"
      >
        <span>
          <i class="feather icon-icon-check"></i> {{ __('Verify payment ') }}
        </span>
      </button>
    @endcan
  @endif
@endsection

@section('content')
<section id="basic-datatable">
  <div class="row">
    <div class="col-7">
      <div class="card">
        <div class="card-content">
          <div class="card-body card-dashboard">
            <h4>
              {{ $row->coursable->course->name }} {{ $row->coursable->course->level->name }}
              <span
                class="
                  badge
                  badge-{{ $row->status->is_approved ? 'success' : ( !$row->status->is_rejected ? 'warning' : 'danger') }}
                "
                style="float: right;"
              >
                {{ $row->status }}
              </span>
              <br>
              <small>
                <b>{{ __('Teacher') }}:</b> {{ $row->coursable->user->fullname }}
              </small>
            </h4>
            <hr>
            <div class="row">
              <div class="col-6">
                <h5>
                  {{ __('Payment') }}
                </h5>
                <p>
                  <b>{{ __('Payment method') }}:</b> {{ $row->payment_method }} <br>
                  @if ($row->payment_method->is_wiretransfer || $row->payment_method->is_apptransfer)
                    <b>{{ __('Bank') }}:</b> {{ $row->bank->name }} <br>
                  @endif
                  <b>{{ __('Amount') }}:</b> {{ number_format($data->sum('amount'), 2) }}<br>
                  <b>
                    {{ __('Voucher') }}:
                    <a href="{{ asset($row->Voucher) }}" target="_blank" rel="noopener noreferrer">{{ __('Show') }}</a>
                  </b>
                </p>
              </div>

              @if ($row->user->personalData->age < 18)
                @php
                  $parent = $row->user->parent->first();
                @endphp
                <div class="col-6">
                  <h5>
                    {{ __('Representative') }}
                  </h5>
                  <p>
                    <i class="feather icon-user"></i> {{ $parent->fullname }} <br>
                    <i class="feather icon-map-pin"></i> {{ $parent->personalData->address->fullAddress }}
                  </p>
                  <p>
                    <i class="feather icon-mail"></i> {{ $parent->email }} <br>
                    <i class="feather icon-phone"></i> {{ $parent->personalData->phone }}
                  </p>
                </div>
              @endif

              <div class="col-6">
                <h5>
                  {{ __('Student') }}
                </h5>
                <p>
                  <i class="feather icon-user"></i> {{ $row->user->fullname }} <br>
                  <i class="feather icon-map-pin"></i> {{ $row->user->personalData->address->fullAddress }}
                </p>
                <p>
                  <i class="feather icon-mail"></i> {{ $row->user->email }} <br>
                  <i class="feather icon-phone"></i> {{ $row->user->personalData->phone }}
                </p>
              </div>

            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-5">
      <div class="card">
        <div class="card-content">
          <div class="card-body card-dashboard">
            <table class="table">
              <thead>
                <tr class="table-secondary">
                  <th colspan="2">
                    <h5 class="mb-0">
                      <b>{{ __('Payment details') }}</b>
                    </h5>
                  </th>
                </tr>
              </thead>
              <tbody>
                @foreach ($data as $item)
                  <tr>
                    <td class="w-70">
                      @if (!$plan->with_inscription)
                        {{ __('Dues') }}
                        <b><span id="dues">{{ $item->dues+1 }}</span></b>
                      @else
                        {{ $item->is_inscription ? __('Inscription') : __('Dues') }}
                        @if (!$item->is_inscription)
                          <b><span id="dues">{{ $item->dues }}</span></b>
                        @endif
                      @endif
                    </td>
                    <td class="text-right p-0 pr-1" style="width: 80px;">
                      {{ number_format($item->amount, 2) }}
                    </td>
                  </tr>
                @endforeach
              </tbody>
              <tfoot>
                <tr>
                  <td class="w-70 text-right pr-1">
                    <h5 class="mb-0">
                      <b>{{ __('Total') }}</b>
                    </h5>
                  </td>
                  <td class="text-right pr-1" style="width: 80px;">
                    <h5 class="mb-0">
                      <b>{{ number_format($data->sum('amount'), 2) }}</b>
                    </h5>
                  </td>
                </tr>
              </tfoot>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
@endsection

@section('vendor-style')
  {{-- vendor css files --}}
  <link rel="stylesheet" href="{{ asset(mix('vendors/css/extensions/sweetalert2.min.css')) }}">
@endsection
@section('page-style')
  @parent
  <!-- Page css files -->
  <style>
    .table td {
      border-color: #d9d9d9 !important;
    }
  </style>
@endsection
@section('vendor-script')
  @parent
  <!-- vendor files -->
  <script src="{{ asset(mix('vendors/js/extensions/sweetalert2.all.min.js')) }}"></script>
@endsection

@section('page-script')
  @parent
  @include('elements.langJs')
  <script>
    let redirectUrl = "{{tenant_route('payments.show', [$row->code])}}";
    let managerUrl = "{{ tenant_route('payments.manager', [$row->code]) }}";
    let token = '{{csrf_token()}}';

    $('.btn-manager').click(function() {
      let data = $(this).data()
      data['_token'] = token

      Swal.fire({
        title: lang.are_you_sure,
        type: 'warning',
        showCancelButton: true,
        confirmButtonColor: '#2ecc71',
        confirmButtonText: lang.yes_sure,
        cancelButtonText: lang.no_cancel,
        showLoaderOnConfirm: true,
        inputAttributes: {
          autocapitalize: 'off'
        },
        preConfirm: () => {
          return fetch(managerUrl, {
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json'
            },
            method: "PUT",
            body: JSON.stringify(data)
          }).catch(error => {
            Swal.showValidationMessage(
              `Request failed: ${error}`
            )
          })
        },
        allowOutsideClick: () => !Swal.isLoading()
      }).then((result) => {
        if (result.value && result.value.ok) {
            Swal.fire({
              title: lang.updated,
              type:'success',
              confirmButtonText: lang.ok,
            }).then(() => {
              window.location.href = redirectUrl
            })
        } else {
            if (result.value)
                Swal.fire({
                  position: 'top-end',
                  type: 'error',
                  title: lang.oops,
                  text: result.value.statusText,
                  showConfirmButton: false,
                  timer: 2500
                })
        }
      })
    });
  </script>
@endsection