routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/', '/app/login', 301);

Route::get('franchises', 'AppController@getFranchises')->name('get.franchises');

//Auth::routes();

app/Models/Tenant/Course.php
<?php

namespace App\Models\Tenant;

use App\Models\System;
use App\Traits\EncryptModel;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\SoftDeletes;
use Tenancy\Affects\Connections\Support\Traits\OnTenant;

class Course extends Model
{
    use OnTenant,
        SoftDeletes,
        EncryptModel;

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'courses';

    /**
     * The relationships that should always be loaded.
     *
     * @var array
     */
    protected $with = ['coursables'];

    /**
     * The attributes that aren't mass assignable.
     *
     * @var array
     */
    protected $guarded = ['id', 'created_at ', 'updated_at' , 'deleted_at'];


    /** Relationships */
    public function branch()
 	{
 		return $this->belongsTo(Branch::class);
    }

    public function language()
 	{
 		return $this->belongsTo(System\Language::class);
    }

    public function level()
 	{
 		return $this->belongsTo(System\ProgramLevel::class, 'level_id');
    }

    public function studentType()
 	{
 		return $this->belongsTo(StudentType::class);
    }

    public function coursables()
    {
        return $this->hasMany(Coursable::class);
    }

    /** Scopes */
    public function scopeCoursable($query, $value)
    {
        return $query->whereHas('coursables', function (Builder $query) use ($value) {
            $query->where('id', $value);
        });
    }

    /** Attributes */
    public function getCoursableAttribute()
    {
        return $this->coursables->where('status', '!=', 'finished')->last();
    }

    public function getDurationWeekAttribute()
    {
        return $this->coursable->duration_week;
    }

    public function getPriceAttribute()
    {
        return number_format($this->coursable->price, 2);
    }

    public function getPlanIdAttribute()
    {
        return $this->coursable->plan_id;
    }
}

app/Models/Tenant/Plan.php
<?php

namespace App\Models\Tenant;

use App\Enums;
use App\Traits\EncryptModel;
use Konekt\Enum\Eloquent\CastsEnums;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\SoftDeletes;
use Tenancy\Affects\Connections\Support\Traits\OnTenant;

class Plan extends Model
{
    use OnTenant,
        CastsEnums,
        SoftDeletes,
        EncryptModel;

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'plans';

    /**
     * The relationships that should always be loaded.
     *
     * @var array
     */
    protected $with = ['features'];

    /**
     * The attributes that aren't mass assignable.
     *
     * @var array
     */
    protected $guarded = ['id', 'created_at', 'updated_at', 'deleted_at'];

    protected $enums = [
        'interval_unit' => Enums\PlanInterval::class,
    ];

    /** Relations */
    public function branches()
    {
        return $this->belongsToMany(Branch::class);
    }

    public function features()
    {
        return $this->hasMany(PlanFeature::class);
    }

    /** Attributes */
    public function getPlanAttribute()
    {
        return $this;
    }

    public function getFullnameAttribute()
    {
        return "{$this->code} {$this->name} ({$this->interval_unit})";
    }

    public function getWithInscriptionAttribute()
    {
        return (boolean) $this->features()->where('type', 'inscription')->count();
    }
}

app/Models/User.php
<?php

namespace App\Models;

use App\Traits;
use App\Models\Tenant;
use Tenancy\Environment;
use App\Traits\GlobalModelConnection;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Tenancy\Affects\Connections\Support\Traits\OnTenant;
use Caffeinated\Shinobi\Concerns\HasRolesAndPermissions;

class User extends Authenticatable
{
    use Notifiable,
        SoftDeletes,
        Traits\UserProfile,
        Traits\EncryptModel,
        HasRolesAndPermissions,
        Traits\GlobalModelConnection;

    /**
     * The attributes that aren't mass assignable.
     *
     * @var array
     */
    protected $guarded = ['id', 'created_at', 'updated_at', 'deleted_at'];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * The relationships that should always be loaded.
     *
     * @var array
     */
    protected $with = [];

    /** Delete Relationships */
    public function deleteRelationships()
    {
        //
    }

    /** Relationships */
    public function branches()
    {
        return $this->belongsToMany(Tenant\Branch::class);
    }

    public function staff()
    {
        return $this->hasOne(Tenant\Staff::class);
    }

    public function personalData()
    {
        return $this->hasOne(Tenant\PersonalData::class);
    }

    public function languages()
    {
        $db = config('database.connections.tenant.database');
        return $this->belongsToMany(System\Language::class, $db.".language_user")
                    ->using(Tenant\LanguageUser::class);
    }

    public function studentType()
    {
        return $this->belongsToMany(Tenant\StudentType::class);
    }

    public function points()
    {
        return $this->hasMany(Tenant\TeacherPoint::class);
    }

    public function enrollment()
    {
        return $this->hasOne(Tenant\StudentEnrollment::class);
    }

    public function parent()
    {
        return $this->belongsToMany(
            User::class, 'parent_children', 'children_id', 'parent_id'
        );
    }

    public function children()
    {
        return $this->belongsToMany(
            User::class, 'parent_children', 'parent_id', 'children_id'
        );
    }

    public function schedules()
    {
        return $this->hasMany(Tenant\Schedule::class);
    }

    public function coursables()
    {
        return $this->hasMany(Tenant\Coursable::class);
    }

    public function courses()
    {
        return $this->belongsToMany(Tenant\Coursable::class)->withPivot('plan_id');
    }

    /** Scopes */
    public function scopeFindRole($query, $value)
    {
        return $query->whereHas('roles', function (Builder $query) use ($value) {
            $query->where('slug', $value);
        });
    }

    public function scopeTeachers($query, $type)
    {
        return $query->whereHas('roles', function (Builder $query) {
            $query->where('slug', 'teacher');
        })->whereHas('staff', function (Builder $query) use ($type) {
            $query->where('type', $type->value());
        });
    }

    public function scopeStudents($query, $status)
    {
        return $query->whereHas('roles', function (Builder $query) {
            $query->where('slug', 'student');
        })->whereHas('enrollment', function (Builder $query) use ($status) {
            $query->where('status', $status->value());
        });
    }

    public function scopeWhereBranch($query, $branch)
    {
        return $query->whereHas('branches', function($query) use ($branch) {
            $query->where('id', $branch);
        });
    }

    public function scopeWhereStudentType($query, $type)
    {
        return $query->whereHas('studentType', function($query) use ($type) {
            $query->where('id', $type);
        });
    }

    public function scopeWhereScheduleDay($query, $days)
    {
        return $query->whereHas('schedules', function($query) use ($days) {
            $query->whereIn('day', $days);
        });
    }

    public function scopeWhereScheduleTime($query, $times)
    {
        return $query->whereHas('schedules', function($query) use ($times) {
            $query->where('start_time', $times['start_time'])
                  ->where('end_time', $times['end_time']);
        });
    }

    public function scopeWhereEnrollmentType($query, $type)
    {
        return $query->whereHas('enrollment', function($query) use ($type) {
            $query->where('student_type_id', $type);
        });
    }

    public function scopeWhereCourse($query, $value)
    {
        return $query->whereHas('courses', function($query) use ($value) {
            $query->where('coursable_id', $value);
        });
    }

    public function scopeWhereDoesntHaveCourse($query, $value)
    {
        return $query->whereDoesntHave('courses', function($query) use ($value) {
            $query->where('coursable_id', $value);
        });
    }

    public function scopeRepresentatives($query)
    {
        return $query->whereHas('roles', function (Builder $query) {
            $query->where('slug', 'representative');
        });
    }

    public function scopeFindByCi($query, $value)
    {
        return $query->whereHas('roles', function (Builder $query) {
            $query->where('slug', 'representative');
        })->whereHas('personalData', function (Builder $query) use ($value) {
            $query->where('ci', $value);
        });
    }

    public function scopeDoesntHaveCourse($query, $value)
    {
        return $query->whereDoesntHave('coursables', function(Builder $query) use ($value) {
            $query->whereHas('days', function(Builder $query) use ($value) {
                    $query->whereIn('day', $value['days']);
            })
            ->where('schedule_id', $value['schedule_id']);
        });
    }

    /** Attributes */
    public function getRoleAttribute()
    {
        return $this->roles->first();
    }

    public function getBranchAttribute()
    {
        return $this->branches->first();
    }

    public function getAddressAttribute()
    {
        return $this->personalData->address;
    }

    public function getStatusAttribute()
    {
        return $this->staff->status;
    }

    public function getTypeAttribute()
    {
        return $this->staff->type;
    }

    public function getRatingsAttribute()
    {
        if ($point = $this->points->where('type', 'general')->first())
            return $point->value;

        return '0.00';
    }

    public function getUserAttribute()
    {
        if ($this->role->slug != 'student')
            $more = [
                'contract_start' => $this->staff
                    ? $this->staff->contract_start : null,
                'contract_end' => $this->staff
                    ? $this->staff->contract_end : null,
                'ranting' => $this->points->pluck('value', 'type'),
                'student' => $this->studentType->pluck('id'),
            ];
        elseif ($this->enrollment)
            $more = ['student' => $this->enrollment->student_type_id];
        else
            $more = [];

        return (Object) array_merge(
            $this->only('username', 'email', 'id'),
            array_merge(
                [
                    'role' => $this->role->slug,
                    'branches' => $this->branches->pluck('id')->toArray(),
                    'languages'=> $this->languages->pluck('id'),
                ],
                $more
            )
        );
    }

    public function getAcademicAttribute()
    {
        if ($data = $this->personalData->academics->first())
            return (Object) array_merge(
                $data->only('dicipline', 'graduate_year'),
                [
                    'type' => $data->type->value(),
                    'title' => $data->title ? $data->title->value() : null,
                    'institution' => $data->institution->name,
                    'is_graduated' => !$data->is_graduated
                ]
            );
        else
            return null;
    }

    public function getRepresentativeAttribute()
    {
        if ($parent = $this->parent->first())
            return (Object) array_merge(
                $parent->personalData->toArray(),
                [ 'profile_photo' => $parent->profile_photo ]
            );
    }

    public function getCiStudentAttribute()
    {
        $ci = $this->personalData->ci;
        $year = $this->personalData->birthdate_year;
        $n = $this->children->count() + 1;

        return "{$n}{$year}{$ci}";
    }

    public function getProfileIsCompleteAttribute ()
    {
        $boo = true;
        $data = collect($this->personalData->toArray())->except(['profile_photo', 'address']);

        foreach ($data as $key => $val)
            if (!$val)
                $boo = false;

        return $boo;
    }
}

resources/views/app/course/_config.blade.php
<div class="row">
  <div class="col-4">
    <div class="form-group">
      <div class="controls">
        <label>{{ __('Branch') }}</label>
        @if (!$franchise->is_multibranch)
          {{ Form::hidden('branch_id', $branches->first()->id, ['id' => 'branch_id']) }}
        @endif
        {{
          Form::select(
            'branch_id',
            $branches->pluck('name', 'id'),
            old('branches') ?? (!$franchise->is_multibranch ? $branches->first()->id : null),
            [
              'id' => $franchise->is_multibranch ? 'branch_id' : '',
              'class' => 'form-control',
              'placeholder' => __('Select :name', [ 'name' => '' ]),
              'required',
              !$franchise->is_multibranch ? 'disabled' : '',
            ]
          )
        }}
      </div>
    </div>
  </div>

  <div class="col-4">
    <div class="form-group">
      <div class="controls">
        <label>{{ __('Language') }}</label>
        {{
          Form::select(
            'language_id',
            [],
            old("language_id"),
            [
              'id' => 'language_id',
              'class' => 'form-control',
              'placeholder' => __('Select :name', [ 'name' => '']),
              'required',
            ]
          )
        }}
      </div>
    </div>
  </div>

  <div class="col-4">
    <div class="form-group">
      <div class="controls">
        <label>{{ __('Level students') }}</label>
        {{
          Form::select(
            'student_type_id',
            $studentType,
            old("student_type_id"),
            [
              'id' => 'student_type_id',
              'class' => 'form-control',
              'placeholder' => __('Select :name', [ 'name' => '' ]),
              'required',
            ]
          )
        }}
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-8">
    <div class="form-group">
      <div class="controls">
        <label>{{ __('Days') }}</label>
        <div class="row col pr-0">
          @php
            $carbon = Carbon\Carbon::today()->startOfWeek()->subDays(2);
          @endphp
          @for ($i = 0; $i < 7; $i++)
            @php $carbon->addDay() @endphp
            <div class="col-6 col-sm-4 px-0">
              <fieldset>
                <div class="vs-checkbox-con vs-checkbox-primary">
                  <input
                    value="1"
                    name="days[{{ $i }}]"
                    type="checkbox"
                    class="checkbox-days"
                    data-day="{{ $i }}"
                    data-label="{{ __($carbon->shortLocaleDayOfWeek) }}"
                  >
                  <span class="vs-checkbox">
                    <span class="vs-checkbox--check">
                      <i class="vs-icon feather icon-check"></i>
                    </span>
                  </span>
                  <span style="font-size: 12px;">
                    {{ __($carbon->format('l')) }}
                  </span>
                </div>
              </fieldset>
            </div>
          @endfor
        </div>
      </div>
    </div>
  </div>
  <div class="col-4">
    <div class="form-group">
      <div class="controls">
        <label>{{ __('Lapse') }}</label>
        {{
          Form::select(
            'schedule_id',
            [],
            old("schedule_id"),
            [
              'id' => 'schedule_id',
              'class' => 'form-control',
              'placeholder' => __('Select :name', [ 'name' => '' ]),
              'required',
            ]
          )
        }}
      </div>
    </div>
  </div>
</div>

@section('vendor-script')
  @parent
  <script src="{{ asset(mix('vendors/js/extensions/moment.min.js')) }}"></script>
@endsection

@section('page-script')
  @parent
  <!-- _config.js -->
  <script>
    const json = {!! $json->toJson() !!}
    let branch_id = language_id = null;
    let coursable = null;

    if ($('#branch_id').val() != '') {
      getLanguages();
      getDataCourse();
    }

    $('#branch_id').change(function() {
      branch_id = $(this).val();
      getLanguages();
      getDataCourse();
    })

    $('#language_id').change(function() {
      language_id = $(this).val();
      $('#student_type_id').removeAttr('disabled');
      getName();
      getDataCourse();
    })

    $('#student_type_id').change(function() {
      getLapse();
      getName();
      getDataCourse();
    })

    $('#schedule_id').change(function () {
      getDataCourse();
    })

    function getDataCourse() {
      let dat = getDataAjax();

      if (
        dat.branch_id != '' &&
        dat.language_id != '' &&
        dat.student_type_id != '' &&
        dat.days.length > 0 &&
        dat.schedule_id != ''
      ) {
        getTeachers()
        getHalls()
        getLevel()
      }
    }

    function getLanguages() {
      let dat = json.find(element => element.id == $('#branch_id').val());
      let options = [];

      for (let index = 0; index < dat.programs.length; index++) {
        const program = dat.programs[index];

        options.push({
          value: program.id,
          text: program.name
        })

      }

      renderOptionSelect($('#language_id'), options)
    }

    function getLapse() {
      let dat = json.find(element => element.id == $('#branch_id').val());
      let options = [];

      for (let index = 0; index < dat.schedules.length; index++) {
        const schedule = dat.schedules[index];
        let start_time = moment.utc(schedule.start_time)
        let end_time = moment.utc(schedule.end_time)

        options.push({
          value: schedule.id,
          text: `${start_time.format('hh:mm A')} - ${end_time.format('hh:mm A')}`
        })
      }

      renderOptionSelect($('#schedule_id'), options)
    }

    function getName() {
      let str = type = '';

      if ($(`select#language_id`).val() != '')
        str = $(`select#language_id option:selected`).text();

      if ($(`select#student_type_id`).val() != '')
        type = $(`select#student_type_id option:selected`).text();

      $('input#name').val(`${str} ${type}`)
      $('div#name').text(`${str} ${type}`)
    }

    async function getTeachers() {
      let url = "{{ tenant_route('teachers.api.index') }}";
      let options = [];
      await ajaxData(url).then(function (data) {
        $.each(data, function (key, val) {
          options.push({
            value: key,
            text: val
          })
        })

        renderOptionSelect($('#user_id'), options)
      })

      if (coursable)
        $(`#user_id option[value="${coursable.user_id}"]`).prop('selected', true);
    }

    async function getHalls() {
      let url = "{{ tenant_route('halls.api.index') }}";
      let options = [];
      await ajaxData(url).then(function (data) {
        $.each(data, function (key, val) {
          options.push({
            value: key,
            text: val
          })
        })

        renderOptionSelect($('#hall_id'), options)
      })

      if (coursable)
        $(`#hall_id option[value="${coursable.hall_id}"]`).prop('selected', true);
    }

    function getLevel() {
      let options = [];
      let dat = json.find(element => element.id == $('#branch_id').val());
      dat = dat.programs.find(element => element.id == $('select#language_id').val());

      for (let index = 0; index < dat.levels.length; index++) {
        const level = dat.levels[index];

        options.push({
          value: level.id,
          text: level.name
        })
      }
      renderOptionSelect($('#level_id'), options)
    }

    function ajaxData(url) {
      return $.ajax({
        url: url,
        data: getDataAjax(),
      });
    }

    function getDataAjax() {
      return {
        branch_id: $('#branch_id').val(),
        language_id: $('select#language_id').val(),
        student_type_id: $('select#student_type_id').val(),
        days: getDataCheckbox(),
        schedule_id: $('select#schedule_id').val(),
        course: "{{ request()->is('app/*/courses/create') }}"
      }
    }

    function getDataCheckbox() {
      let array = []
      let checkbox = $('.checkbox-days:checked')

      for (let index = 0; index < checkbox.length; index++)
        array.push($(checkbox[index]).data('day'))

      return array
    }

    function renderOptionSelect(select, options) {
      $(select).children('option').remove()
      $(select).append(`
        <option>{{ __('Select :name', [ 'name' => '...' ]) }}</option>
      `);

      for (let index = 0; index < options.length; index++) {
          const option = options[index];
          $(select).append(`
            <option value="${option.value}">${option.text}</option>
          `)
      }

      $(select).removeAttr('disabled')
    }

  </script>
  @isset($data)
  <script>
    initRenderData()

    function initRenderData() {
      getLanguages();
      $('#student_type_id').removeAttr('disabled');
      getLapse();

      $(`#language_id option[value="${data.language_id}"]`).prop('selected', true);
      coursable = data.coursables[data.coursables.length -1];
      $(`#schedule_id option[value="${coursable.schedule_id}"]`).prop('selected', true);

      $.each(coursable.days, function (key, row) {
        $(`.checkbox-days[name="days[${row.day}]"]`).prop('checked', true);
      });

      getName();
      getTeachers();
      getHalls();
      getLevel();
      $(`#level_id option[value="${data.level_id}"]`).prop('selected', true);
    }
  </script>
  @endisset
@endsection

resources/views/app/course/_data.blade.php
<div class="row">
  <div class="col-6">
    <div class="form-group">
      <div class="controls">
        <label>{{ __('Teacher') }}</label>
        {{
          Form::select(
            'user_id',
            [],
            old("user_id"),
            [
                'id' => 'user_id',
                'class' => 'form-control',
                'placeholder' => __('Select :name', [ 'name' => '' ]),
                'required',
            ]
          )
        }}
      </div>
    </div>
  </div>

  <div class="col-6">
    <div class="form-group">
      <div class="controls">
        <label>{{ __('Hall') }}</label>
        {{
          Form::select(
            'hall_id',
            [],
            old("hall_id"),
            [
                'id' => 'hall_id',
                'class' => 'form-control',
                'placeholder' => __('Select :name', [ 'name' => '' ]),
                'required',
            ]
          )
        }}
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-6">
    <label class="form-lable">@lang('Name course')</label>
    <input type="hidden" name="name" id="name">
    <div id="name"></div>
  </div>
  <div class="col-6">
    <div class="form-group">
      <div class="controls">
        <label>{{ __('Level') }}</label>
        {{
          Form::select(
            'level_id',
            [],
            old("level_id"),
            [
                'id' => 'level_id',
                'class' => 'form-control',
                'placeholder' => __('Select :name', [ 'name' => '' ]),
                'required',
            ]
          )
        }}
      </div>
    </div>
  </div>
</div>

resources/views/app/course/index.blade.php
@extends('layouts/default')

@section('title', __('Courses'))

@section('btn-action')
  @can('courses.create')
    <a
      href="{{ tenant_route('courses.create') }}"
      class="btn btn-outline-primary"
    >
      <span>
        <i class="feather icon-plus"></i> {{ __('Add New') }}
      </span>
    </a>
  @endcan
@endsection

@section('content')
<section id="basic-datatable">
  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-content">
          <div class="card-body card-dashboard">
            <div class="table-responsive">
              <table class="table">
                <thead>
                    <tr>
                      <th>{{__('Course')}}</th>
                      <th class="no-sort">{{__('Teacher')}}</th>
                      @if($franchise->is_multibranch)
                        <th  class="sort">{{__('Branch')}}</th>
                      @endif
                      <th class="no-sort">{{__('Hall')}}</th>
                      <th class="no-sort">{{__('Capacity')}}</th>
                      <th class="no-sort">{{__('Status')}}</th>
                      <th class="no-sort" style="width: 15%">&nbsp;</th>
                    </tr>
                </thead>
                <tbody>
                  @foreach($rows as $course)
                    @php
                      if(!$coursable = $course->coursables->last())
                        continue;
                    @endphp
                    <tr id="row-{{ $coursable->hid }}">
                      <td>{{ $course->name }} {{ $course->level->name }}</td>
                      <td>{{ $coursable->user->fullname }}</td>
                      @if($franchise->is_multibranch)
                        <td>{{ $course->branch->name }}</td>
                      @endif
                      <td>{{ $coursable->hall->name }}</td>
                      <td>
                        @php
                          $phcapacy = ($coursable->students->count() / $coursable->hall->capacity) * 100;
                          $badgeClass = 'primary';

                          if ($phcapacy <= 40)
                            $badgeClass = 'success';
                          elseif ($phcapacy > 40 && $phcapacy <= 70)
                            $badgeClass = 'warning';
                          else
                            $badgeClass = 'danger';
                        @endphp
                        <h3 class="badge badge-{{ $badgeClass }}">
                            {{ $coursable->students->count() }} <small>/ {{ $coursable->hall->capacity }}</small>
                        </h3>
                      </td>
                      <td>
                        @php
                          $badgeClass = $coursable->status->is_inpro
                              ? 'success'
                              : ( $coursable->status->is_finis ? 'danger' : 'warning');
                        @endphp
                        <span class="badge badge-{{ $badgeClass }}">
                            {{ $coursable->status }}
                        </span>
                      </td>
                      <td class="text-left">
                        @if (!$coursable->status->is_finis)
                          @can('courses.manager')
                            <a
                              href="{{ tenant_route('courses.students', [$course->hid]) }}"
                              class="btn btn-sm btn-secondary btn-edit m-r-5"
                              data-toggle="tooltip"
                              data-original-title="{{__('Add :type', ['type' => __('Student')])}}"
                            >
                              <i class="fa fa-user-plus font-14"></i>
                            </a>
                          @endcan
                          @can('courses.edit')
                            <a
                              href="{{ tenant_route('courses.edit', [$course->hid]) }}"
                              class="btn btn-sm btn-primary btn-edit m-r-5"
                              data-toggle="tooltip"
                              data-original-title="{{__('Edit')}}"
                            >
                              <i class="fa fa-pencil font-14"></i>
                            </a>
                          @endcan
                        @endif
                        @can('teachers.delete')
                          <button
                            type="button"
                            data-id="{{ $course->hid }}"
                            class="btn btn-sm btn-danger btn-delete"
                            data-toggle="tooltip"
                            data-original-title="{{__('Remove')}}"
                          >
                            <i class="fa fa-trash font-14"></i>
                          </button>
                        @endcan
                      </td>
                    </tr>
                  @endforeach
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
@endsection

@section('vendor-style')
  {{-- vendor css files --}}
  <link rel="stylesheet" href="{{ asset(mix('vendors/css/tables/datatable/datatables.min.css')) }}">
  <link rel="stylesheet" href="{{ asset(mix('vendors/css/animate/animate.css')) }}">
  <link rel="stylesheet" href="{{ asset(mix('vendors/css/extensions/sweetalert2.min.css')) }}">
@endsection
@section('vendor-script')
{{-- vendor files --}}
  <script src="{{ asset(mix('vendors/js/tables/datatable/pdfmake.min.js')) }}"></script>
  <script src="{{ asset(mix('vendors/js/tables/datatable/vfs_fonts.js')) }}"></script>
  <script src="{{ asset(mix('vendors/js/tables/datatable/datatables.min.js')) }}"></script>
  <script src="{{ asset(mix('vendors/js/tables/datatable/datatables.buttons.min.js')) }}"></script>
  <script src="{{ asset(mix('vendors/js/tables/datatable/buttons.html5.min.js')) }}"></script>
  <script src="{{ asset(mix('vendors/js/tables/datatable/buttons.print.min.js')) }}"></script>
  <script src="{{ asset(mix('vendors/js/tables/datatable/buttons.bootstrap.min.js')) }}"></script>
  <script src="{{ asset(mix('vendors/js/tables/datatable/datatables.bootstrap4.min.js')) }}"></script>
  <script src="{{ asset(mix('vendors/js/extensions/sweetalert2.all.min.js')) }}"></script>
  <script src="{{ asset(mix('vendors/js/extensions/polyfill.min.js')) }}"></script>
@endsection
@section('page-script')
  @parent
  @include('elements.langJs')
  <script>
    var routeDelete = "{{ tenant_route('courses.destroy', [':id']) }}";
    var routeIndex = "{{ tenant_route('courses.index') }}";
    var csrfToken = "{{csrf_token()}}";
    var configTable = {
      ordering: false,
      columnDefs: [{
        targets: 'sort',
        orderable: true,
      }],
      language: {
        url: "{{ asset('json/datatable/'.App::getLocale().'.json') }}"
      }
    }
  </script>
  <script src="{{ asset(mix('js/scripts/basic-crud.js')) }}"></script>
@endsection